name: build
on: [push, pull_request]
jobs:
    build:
        name: Build
        runs-on: windows
        steps:
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.19

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Test
              run: |
                  go build .
                  go test -v
